apiVersion: v2
name: jenkins
home: https://jenkins.io/
version: 7.8.41
appVersion: 2.426.1
description: Jenkins - Build great things at any scale! The leading open source automation server, Jenkins provides over 1800 plugins to support building, deploying and automating any project.
sources:
  - https://github.com/jenkinsci/jenkins
  - https://github.com/jenkinsci/docker-inbound-agent
  - https://github.com/maorfr/kube-tasks
  - https://github.com/jenkinsci/configuration-as-code-plugin
maintainers:
  - name: maorfr
    email: maor.friedman@redhat.com
  - name: torstenwalter
    email: mail@torstenwalter.de
  - name: mogaal
    email: garridomota@gmail.com
  - name: wmcdona89
    email: wmcdona89@gmail.com
  - name: timja
    email: timjacomb1@gmail.com
icon: https://get.jenkins.io/art/jenkins-logo/logo.svg
keywords:
  - jenkins
  - ci
  - devops
